env: "prod"

http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s

db:
  user: "walletsuser"
  name: "wallets-db"
  host: "wallets.db"
  port: "5432"
  sslmode: "disable"

redis:
  address: "redis"
  port: "6379"
  db: 0
  lock_exporation: 500ms
  cache_exporation: 2m
  max_unlock_retries: 20
  base_retry_delay: 50ms